language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  app: taigirfrontendappsoap
  on:
    repo: hdushan/taigirfrontendappsoap
  api_key:
    secure: t3RsgAwpoujywnNbO4zJSVkgdO1phC3VD/np2ovaiLjuA5NG/RY88Rt9egF5Af/HqJFzwZNeahM/YPfhDxfDw9iA5Xrb6pDsTZCKHVIDcKF1U99kGsE5rXvesqhk9BFacNf9NyrwpjGZtWDAOXHc+OEB8LiTbTnmpKTPmfJYMo+Nznb4dVg74GIvNrYw8kuEqOk16gdEnLPuwhPrbkj309a0/N049QAhNduF5ar0BglLw4IQmwVwtOdHgxDFOApaD1KQ7DC9vUmmI2Ss9pF+nB+ZUN0AralavbWtEyIgiLs074M+u/bnaD5EchxJO7/Mw3UOztJk74pWrcTyH+QYr3gRUTAHlD/5HaikpJ5YdOc2ypZFosjGB755rM7ifxMT+oYN+N2C3MmChoW49u4+PhFnZIyM4hKY5pmP5z6xKy24QGY6piT5jbN/M14OKAF4alcbSTrJOWC1+kJRBdlLrGjUXvlM/cItP8FDO7NR+LQoI7h+jgexz02IN3bHvTqJI+ZmYZ138fWvadjvIy4v+pTs9tSmgIRjC5Wra8YGsWk9wrpTd0KMB7Cl9Z7ugTZhh7sVjRSwn1Vuz3rKSSZxBJ1mIsCgMy+GY3BNNgew+Qi5w50ksarnSC/biY8jLR8Ezoqa3uUXwJOoGXM+AAf5fBMsTNMmypG+rtWPojK5gyc=
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
