language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  api_key:
    secure: Fva+8Cz3V9rpPWV5Xh9V55VyXxOqYFzy82CpkateI8SSA7xHbE1huZ4k08kyllGa84IDmyZbSvphMZzkF/IX6q/Ydv90quN7X/nNAXUrtg77y7RA5NKePvj6SZPdt9imtUGPljVQrEv34pKW4xpHzej6rMEqbctHxpje42J1zWf90JMLVhJvtFY7VrZJ43yOIUhk2xDPc34brCyIVJRrdCUweoHTk+q29+GoTmGRbIbidJOv7oOb5FbVTmjFJA4zZHVIyTw1bNW2cddLjyV+1KIX03Zx+lRCqm9LlSD6k8TF8FFY7XKUsTgZlTpmuKqxY/Jb22nD59sgx1sqOL7JeeDop6XEJjhLq7IN5c8wtg+fpwifnpIlIOHxqLiQ6c9KKsgmkukUmuI1f/Jn8/Ui+et03o9F/FF1cJUl/5hi58Ur41lNTKaLefDT2c3x1dkUxH+EJQ3+Cvsboz2oWSfwBTaNyNmoL9atUlvMQ5zdyc/JYxkaW+afDCvq/JaUEdoJ2WlJFCWmH/6c8/xo6dB3semPkQDuRlxK3CEcNbQRnpPKyVahpRH9OxMNnwTeKFRSZa6GJFY0Xb0jsUQJ9kK76rT09tFyTn+A0tT73Du0g3BMcsqVsSAVrCqTz9ArKFmavczSayRsVx5E7eREl1u6kgnofm7RdL3A5kAAIbkyymY=
  app: taigirfrontendappsoap
  on:
    repo: hdushan/taigirFrontEndAppSOAP
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
